# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mini projet sim' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mini projet sim
 pod 'razorpay-pod', '~> 1.1.1'
 pod 'Alamofire'
 pod 'GoogleSignIn'
 pod 'Firebase/Core'
 pod 'Firebase/AdMob'
 pod 'Google-Mobile-Ads-SDK'
 pod 'SwiftyJSON'	
  target 'mini projet simTests' do
    inherit! :search_paths
    # Pods for testing
  end


  target 'mini projet simUITests' do
    # Pods for testing
  end 
end
